name: Build and deploy code to Dockerhub

on: [push, pull_request]

jobs:
  lint_python:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: lint python
        uses: py-actions/flake8@v2
        with:
          ignore: "E501"
          max-line-length: "100"
          path: "app"
  deploy:
    runs-on: ubuntu-latest
    needs: [lint_python]
    name: Deploy to Dockerhub
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{steps.buildx.outputs,name}}
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/proxy-http:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{steps.docker_buiöd.outputs.digest}}
