name: Build and deploy code to Dockerhub

on: [push, pull_request]

jobs:
  lint_python:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Checkout code
        uses: suo/flake8-github-action@releases/v1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{secrets.MY_TOKEN}}
    