name: Build and deploy code to Dockerhub

on: [push, pull_request]

jobs:
  run_action_valid_flake8_version:
    name: Test run action (valid with Flake 3.8.0)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
       with:
        path: example_valid
        flake8_version: 3.8.0