name: Build and deploy code to Dockerhub

on: [push, pull_request]

jobs:
  lint_python:
    name: Lint code base
    runs-on: ubuntu-latest
    name: Lint Python code base
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E501"
          max-line-length: "100"
          path: "app"
    